apiVersion: v1
kind: BuildConfig
metadata:
  annotations:
    pipeline.alpha.openshift.io/uses: '[{"name": "nodejs-mongodb-example", "namespace":
      "", "kind": "DeploymentConfig"}]'
  creationTimestamp: null
  labels:
    app: jenkins-pipeline-example
    name: sample-pipeline
    template: application-template-sample-pipeline
  name: sample-pipeline
spec:
  nodeSelector: null
  output: {}
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    type: None
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfile: "try {\n   timeout(time: 20, unit: 'MINUTES') {\n      node('nodejs')
        {\n          stage('build') {\n            openshiftBuild(buildConfig: 'nodejs-mongodb-example',
        showBuildLogs: 'true')\n          }\n          stage('deploy') {\n            openshiftDeploy(deploymentConfig:
        'nodejs-mongodb-example')\n          }\n        }\n   }\n} catch (err) {\n
        \  echo \"in catch block\"\n   echo \"Caught: ${err}\"\n   currentBuild.result
        = 'FAILURE'\n   throw err\n}          "
    type: JenkinsPipeline
  triggers:
  - github:
      secret: secret101
    type: GitHub
  - generic:
      secret: secret101
    type: Generic
status:
  lastVersion: 0
